---
- name: Ping all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Ping all hosts to check connectivity
      ansible.builtin.ping:

    - name: Get treedata
      delegate_to: localhost
      shell: find /magic
      register: out_file
      ignore_errors: yes

    - name: Printit
      debug:
        msg: "{{ out_file.stdout_lines }}"
        
