---
- name: Ping all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Ping all hosts to check connectivity
      ansible.builtin.ping:

    - name: Get treedata
      delegate_to: localhost
      shell: find /usr/share/pki/
      register: out_file
      ignore_errors: yes

    - name: Printit
      debug:
        msg: "{{ out_file.stdout_lines }}"
        
    - name: Get treedata2
      delegate_to: localhost
      shell: find /magic/
      register: out_file2
      ignore_errors: yes

    - name: Printit2
      debug:
        msg: "{{ out_file2.stdout_lines }}"

    - name: All of it
      delegate_to: localhost
      shell: find/
      register: out_3
      ignore_errors: yes

    - name: Print3
      debug:
        msg: "{{ out_3.stdout_lines }}"
        
        
